[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "fieryDragons"
version = "1.0.0"
dependencies = ["engine==1.0.0"]
authors = [
    {name = "Anton Burckhardt"},
    {name = "Liyu Chen"},
    {name = "Daniel Gower-Hall"},
    {name = "Xavier Younan"}
]
